.TH REGIONDUMP 1 2026 nbtfsutils

.SH NAME
regiondump - Dump all information of a Minecraft Region file
.SH SYNOPSIS
.nf
regiondump \fI<path>\fR
.fi
.SH DESCRIPTION
.B regiondump
displays header information of available chunks, and an NBT tree dump in text form, of every available chunk, from the Minecraft Region file specified by \fI<path>\fR.
.SH BUGS
Dumping all chunks in text form from a region file usually outputs a large amount of text, which could flood the terminal of an unprepared user.
It should support some options to allow dumping only the region header or some specified chunks instead of all information.
